# -*- coding: utf-8 -*-
"""TrabalhoED.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qvnsANB2XE0SaRXUF0-pdECblgjUnosT

#População brasileira e americana, características, comparações como idade longevidade, média salarial, etc;

---
"""

import pandas as pd
import matplotlib.pyplot as plt
dados=pd.read_excel("Dados.xlsx",sheet_name=0)

display(dados)

"""# Comparação Populacional entre Brasil e Estados Unidos"""

popu=(dados.loc[dados['Indicador'] == 'População total'])
display(popu)

x1=['2015','2016','2017','2018','2019','2020']
y1=[319929162,323015992,325084758,327096263,329064917,331002647]
x2=['2015','2016','2017','2018','2019','2020']
y2=[204471759,206163056,207833825,209469320,211049519,212559409	]
plt.figure(figsize=(20,10))
plt.xlabel('Anos')
plt.ylabel('Habitantes/Milhões')
plt.plot (x1,y1,'o-m',label='Estados Unidos')
plt.plot(x2,y2,'o-g',label='Brasil')
plt.legend()
plt.axis(ymin=100000000,ymax=400000000)
plt.title('População Brasil/Estados Unidos(2015-2020)',color='blue')
plt.show

"""# Expectativa de vida (Brasil/Estados Unidos)"""

expect=(dados.loc[dados['Indicador'] == 'Esperança-a de vida ao nascer'])
display(expect)

usx1=['2014','2015','2016','2017','2018','2019']
usy1=[78.9,78.9,78.9,78.9,78.9,78.9]
brx2=['2014','2015','2016','2017','2018','2019']
bry2=[74.7,75.0,75.2,75.5,75.7,75.9]
largura=0.35
laguran=-0.35
plt.figure(figsize=(20,10))
plt.xlabel('Anos')
plt.ylabel('Anos de vida')
plt.bar (usx1  ,usy1,largura,label='Estados Unidos',color='c', align='edge')
plt.bar (brx2 ,bry2,laguran,label='Brasil',color='y',align='edge')
plt.legend()
plt.axis(ymin=70,ymax=80)
plt.title('Expectativa de vida(2014-2019)',color='b')
plt.show

"""# Gastos com educação"""

educ=(dados.loc[dados['Indicador'] == 'Gastos públicos com educação'])
display(educ)

gpx1=['2011','2012','2013','2014']
gpy1=[5.2,5.2,4.9,5.0]
gpx2=['2011','2012','2013','2014']
gpy2=[5.6,5.7,5.9,5.8]
largura=0.35
laguran=-0.35
plt.figure(figsize=(20,10))
plt.xlabel('Anos')
plt.ylabel('% do PIB')
plt.bar (gpx1,gpy1,largura,label='Estados Unidos',color='c', align='edge')
plt.bar (gpx2 ,gpy2,laguran,label='Brasil',color='chocolate',align='edge')
plt.legend()
plt.axis(ymin=4,ymax=7)
plt.title('Gastos públicos com educação	(2011-2014)',color='b')
plt.show

"""# Total do PIB
## O PIB é a soma de todos os bens e serviços finais produzidos por um país, estado ou cidade, geralmente em um ano. Todos os países calculam o seu PIB nas suas respectivas moedas.
"""

pib=(dados.loc[dados['Indicador'] == 'Total do PIB'])
display(pib)

usx1=['2014','2015','2016','2017','2018','2019']
usy1=[17527258,18238301,18745075,19542980,20611861,21433226]
brx2=['2014','2015','2016','2017','2018','2019']
bry2=[2472819,2456044,1802212,1795693,2062838,1885469]
largura=0.35
laguran=-0.35
plt.figure(figsize=(20,10))
plt.xlabel('Anos')
plt.ylabel('PIB')
plt.bar (usx1  ,usy1,largura,label='Estados Unidos',color='hotpink', align='edge')
plt.bar (brx2 ,bry2,laguran,label='Brasil',color='y',align='edge')
plt.legend()
plt.axis(ymin=70000,ymax=30000000)
plt.title('Total do PIB(2014-2019)',color='b')
plt.show

"""# Índice de Desenvolvimento Humano
## O Índice de Desenvolvimento Humano (IDH) é uma medida resumida do progresso a longo prazo em três dimensões básicas do desenvolvimento humano: renda, educação e saúde. O objetivo da criação do IDH foi o de oferecer um contraponto a outro indicador muito utilizado, o Produto Interno Bruto (PIB) per capita, que considera apenas a dimensão econômica do desenvolvimento. Criado por Mahbub ul Haq com a colaboração do economista indiano Amartya Sen, ganhador do Prêmio Nobel de Economia de 1998, o IDH pretende ser uma medida geral e sintética que, apesar de ampliar a perspectiva sobre o desenvolvimento humano, não abrange nem esgota todos os aspectos de desenvolvimento.
"""

idh=(dados.loc[dados['Indicador'] == 'Índice de desenvolvimento humano'])
display(idh)
usx1=['2014','2015','2016','2017','2018','2019']
usy1=[0.915,0.921,0.922,0.924,0.925,0.926]
brx2=['2014','2015','2016','2017','2018','2019']
bry2=[0.755,0.756,0.758,0.761,0.762,0.765]
largura=0.35
laguran=-0.35
plt.figure(figsize=(15,10))
plt.xlabel('Anos')
plt.ylabel('IDH')
plt.plot (usx1  ,usy1,'^-m',label='Estados Unidos')
plt.plot (brx2 ,bry2,'^-g',label='Brasil')
plt.legend()
plt.axis(ymin=0.5,ymax=1)
plt.title('Indice de desenvolvimeto Humano(2014-2019)',color='b')
plt.show